server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/DocumentSystem
    username: postgres
    password: postgres
  #JPA Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #spring.jpa.show-sql=true
        format_sql: TRUE
    hibernate:
      ddl-auto: update
    open-in-view: false